[build]
  publish = "."
  command = "npm install --prefix functions && echo 'Build completed - all files should be included'"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Debug-Source = "static-js-file"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Functions configuration already specified in [build] section

# ✅ STATIC FILES PASSTHROUGH
[[redirects]]
  from = "/config/*.js"
  to = "/config/:splat"
  status = 200

[[redirects]]
  from = "/js/*.js"  
  to = "/js/:splat"
  status = 200

# ✅ SPA FALLBACK - SEMPRE ULTIMO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = {X-Debug-Source = "spa-fallback"}