[build]
  publish = "."
  command = "npm install --prefix functions && echo 'Build completed - all files should be included'"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Debug-Source = "static-js-file"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Functions configuration already specified in [build] section

# 🚀 API REDIRECTS - Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

# ✅ STATIC FILES PASSTHROUGH - Fix redirect priority

# Fix per file JS nella root
[[redirects]]
  from = "/config-modules.js"
  to = "/config-modules.js"
  status = 200
  force = false

[[redirects]]
  from = "/temporal-*.js"
  to = "/temporal-:splat.js"
  status = 200
  force = false

[[redirects]]
  from = "/italian-*.js"
  to = "/italian-:splat.js"
  status = 200
  force = false

# Fix per cartelle specifiche
[[redirects]]
  from = "/js/temporal/*"
  to = "/js/temporal/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/js/middleware/*"
  to = "/js/middleware/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/js/config/*"
  to = "/js/config/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/config/*"
  to = "/config/:splat"
  status = 200
  force = false

# 🎯 FIX SPECIFICO con FORCE per file temporal e italian
[[redirects]]
  from = "/temporal-:name.js"
  to = "/config/temporal-:name.js"
  status = 200
  force = true
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/italian-:name.js"
  to = "/js/utils/italian-:name.js"
  status = 200
  force = true
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/js/temporal/*"
  to = "/js/temporal/:splat"
  status = 200
  force = true
  headers = {Content-Type = "application/javascript"}

# 🔄 ROOT-JS → /js/ (catch-all per altri file JS nella root)
[[redirects]]
  from = "/:file.js"
  to = "/js/:file.js"
  status = 200
  force = false

# ✅ SPA FALLBACK - SEMPRE ULTIMO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = {X-Debug-Source = "spa-fallback"}